[packaging]
package_name = "azure-bing-language-spellcheck"
package_nspkg = "azure-bing-language-nspkg"
package_pprint_name = "MyService Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = true
