# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import ErrorDetails
    from ._models_py3 import ErrorResponse, ErrorResponseException
    from ._models_py3 import MeterDetails
    from ._models_py3 import Operation
    from ._models_py3 import OperationDisplay
    from ._models_py3 import ProxyResource
    from ._models_py3 import Resource
    from ._models_py3 import ResourceAttributes
    from ._models_py3 import SkuProperty
    from ._models_py3 import Tag
    from ._models_py3 import TagsResult
    from ._models_py3 import UsageDetail
except (SyntaxError, ImportError):
    from ._models import ErrorDetails
    from ._models import ErrorResponse, ErrorResponseException
    from ._models import MeterDetails
    from ._models import Operation
    from ._models import OperationDisplay
    from ._models import ProxyResource
    from ._models import Resource
    from ._models import ResourceAttributes
    from ._models import SkuProperty
    from ._models import Tag
    from ._models import TagsResult
    from ._models import UsageDetail
from ._paged_models import OperationPaged
from ._paged_models import UsageDetailPaged
from ._consumption_management_client_enums import (
    Metrictype,
    Scope2,
)

__all__ = [
    'ErrorDetails',
    'ErrorResponse', 'ErrorResponseException',
    'MeterDetails',
    'Operation',
    'OperationDisplay',
    'ProxyResource',
    'Resource',
    'ResourceAttributes',
    'SkuProperty',
    'Tag',
    'TagsResult',
    'UsageDetail',
    'UsageDetailPaged',
    'OperationPaged',
    'Metrictype',
    'Scope2',
]
