# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model
from msrest.exceptions import HttpOperationError


class AspectConfidenceScoreLabel(Model):
    """Represents the confidence scores across all sentiment classes: positive,
    neutral, negative.

    All required parameters must be populated in order to send to Azure.

    :param positive: Required.
    :type positive: float
    :param negative: Required.
    :type negative: float
    """

    _validation = {
        'positive': {'required': True},
        'negative': {'required': True},
    }

    _attribute_map = {
        'positive': {'key': 'positive', 'type': 'float'},
        'negative': {'key': 'negative', 'type': 'float'},
    }

    def __init__(self, **kwargs):
        super(AspectConfidenceScoreLabel, self).__init__(**kwargs)
        self.positive = kwargs.get('positive', None)
        self.negative = kwargs.get('negative', None)


class AspectRelation(Model):
    """AspectRelation.

    All required parameters must be populated in order to send to Azure.

    :param relation_type: Required. The type related to the aspect. Possible
     values include: 'opinion', 'aspect'
    :type relation_type: str or
     ~azure.ai.textanalytics.v3_1_preview_2.models.AspectRelationType
    :param ref: Required. The JSON pointer indicating the linked object.
    :type ref: str
    """

    _validation = {
        'relation_type': {'required': True},
        'ref': {'required': True},
    }

    _attribute_map = {
        'relation_type': {'key': 'relationType', 'type': 'AspectRelationType'},
        'ref': {'key': 'ref', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(AspectRelation, self).__init__(**kwargs)
        self.relation_type = kwargs.get('relation_type', None)
        self.ref = kwargs.get('ref', None)


class DetectedLanguage(Model):
    """DetectedLanguage.

    All required parameters must be populated in order to send to Azure.

    :param name: Required. Long name of a detected language (e.g. English,
     French).
    :type name: str
    :param iso6391_name: Required. A two letter representation of the detected
     language according to the ISO 639-1 standard (e.g. en, fr).
    :type iso6391_name: str
    :param confidence_score: Required. A confidence score between 0 and 1.
     Scores close to 1 indicate 100% certainty that the identified language is
     true.
    :type confidence_score: float
    """

    _validation = {
        'name': {'required': True},
        'iso6391_name': {'required': True},
        'confidence_score': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'iso6391_name': {'key': 'iso6391Name', 'type': 'str'},
        'confidence_score': {'key': 'confidenceScore', 'type': 'float'},
    }

    def __init__(self, **kwargs):
        super(DetectedLanguage, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.iso6391_name = kwargs.get('iso6391_name', None)
        self.confidence_score = kwargs.get('confidence_score', None)


class DocumentEntities(Model):
    """DocumentEntities.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. Unique, non-empty document identifier.
    :type id: str
    :param entities: Required. Recognized entities in the document.
    :type entities: list[~azure.ai.textanalytics.v3_1_preview_2.models.Entity]
    :param warnings: Required. Warnings encountered while processing document.
    :type warnings:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.TextAnalyticsWarning]
    :param statistics: if showStats=true was specified in the request this
     field will contain information about the document payload.
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.DocumentStatistics
    """

    _validation = {
        'id': {'required': True},
        'entities': {'required': True},
        'warnings': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'entities': {'key': 'entities', 'type': '[Entity]'},
        'warnings': {'key': 'warnings', 'type': '[TextAnalyticsWarning]'},
        'statistics': {'key': 'statistics', 'type': 'DocumentStatistics'},
    }

    def __init__(self, **kwargs):
        super(DocumentEntities, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.entities = kwargs.get('entities', None)
        self.warnings = kwargs.get('warnings', None)
        self.statistics = kwargs.get('statistics', None)


class DocumentError(Model):
    """DocumentError.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. Document Id.
    :type id: str
    :param error: Required. Document Error.
    :type error:
     ~azure.ai.textanalytics.v3_1_preview_2.models.TextAnalyticsError
    """

    _validation = {
        'id': {'required': True},
        'error': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'error': {'key': 'error', 'type': 'TextAnalyticsError'},
    }

    def __init__(self, **kwargs):
        super(DocumentError, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.error = kwargs.get('error', None)


class DocumentKeyPhrases(Model):
    """DocumentKeyPhrases.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. Unique, non-empty document identifier.
    :type id: str
    :param key_phrases: Required. A list of representative words or phrases.
     The number of key phrases returned is proportional to the number of words
     in the input document.
    :type key_phrases: list[str]
    :param warnings: Required. Warnings encountered while processing document.
    :type warnings:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.TextAnalyticsWarning]
    :param statistics: if showStats=true was specified in the request this
     field will contain information about the document payload.
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.DocumentStatistics
    """

    _validation = {
        'id': {'required': True},
        'key_phrases': {'required': True},
        'warnings': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'key_phrases': {'key': 'keyPhrases', 'type': '[str]'},
        'warnings': {'key': 'warnings', 'type': '[TextAnalyticsWarning]'},
        'statistics': {'key': 'statistics', 'type': 'DocumentStatistics'},
    }

    def __init__(self, **kwargs):
        super(DocumentKeyPhrases, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.key_phrases = kwargs.get('key_phrases', None)
        self.warnings = kwargs.get('warnings', None)
        self.statistics = kwargs.get('statistics', None)


class DocumentLanguage(Model):
    """DocumentLanguage.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. Unique, non-empty document identifier.
    :type id: str
    :param detected_language: Required. Detected Language.
    :type detected_language:
     ~azure.ai.textanalytics.v3_1_preview_2.models.DetectedLanguage
    :param warnings: Required. Warnings encountered while processing document.
    :type warnings:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.TextAnalyticsWarning]
    :param statistics: if showStats=true was specified in the request this
     field will contain information about the document payload.
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.DocumentStatistics
    """

    _validation = {
        'id': {'required': True},
        'detected_language': {'required': True},
        'warnings': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'detected_language': {'key': 'detectedLanguage', 'type': 'DetectedLanguage'},
        'warnings': {'key': 'warnings', 'type': '[TextAnalyticsWarning]'},
        'statistics': {'key': 'statistics', 'type': 'DocumentStatistics'},
    }

    def __init__(self, **kwargs):
        super(DocumentLanguage, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.detected_language = kwargs.get('detected_language', None)
        self.warnings = kwargs.get('warnings', None)
        self.statistics = kwargs.get('statistics', None)


class DocumentLinkedEntities(Model):
    """DocumentLinkedEntities.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. Unique, non-empty document identifier.
    :type id: str
    :param entities: Required. Recognized well-known entities in the document.
    :type entities:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.LinkedEntity]
    :param warnings: Required. Warnings encountered while processing document.
    :type warnings:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.TextAnalyticsWarning]
    :param statistics: if showStats=true was specified in the request this
     field will contain information about the document payload.
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.DocumentStatistics
    """

    _validation = {
        'id': {'required': True},
        'entities': {'required': True},
        'warnings': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'entities': {'key': 'entities', 'type': '[LinkedEntity]'},
        'warnings': {'key': 'warnings', 'type': '[TextAnalyticsWarning]'},
        'statistics': {'key': 'statistics', 'type': 'DocumentStatistics'},
    }

    def __init__(self, **kwargs):
        super(DocumentLinkedEntities, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.entities = kwargs.get('entities', None)
        self.warnings = kwargs.get('warnings', None)
        self.statistics = kwargs.get('statistics', None)


class DocumentSentiment(Model):
    """DocumentSentiment.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. Unique, non-empty document identifier.
    :type id: str
    :param sentiment: Required. Predicted sentiment for document (Negative,
     Neutral, Positive, or Mixed). Possible values include: 'positive',
     'neutral', 'negative', 'mixed'
    :type sentiment: str or
     ~azure.ai.textanalytics.v3_1_preview_2.models.DocumentSentimentValue
    :param statistics:
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.DocumentStatistics
    :param confidence_scores: Required. Document level sentiment confidence
     scores between 0 and 1 for each sentiment class.
    :type confidence_scores:
     ~azure.ai.textanalytics.v3_1_preview_2.models.SentimentConfidenceScorePerLabel
    :param sentences: Required. Sentence level sentiment analysis.
    :type sentences:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.SentenceSentiment]
    :param warnings: Required. Warnings encountered while processing document.
    :type warnings:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.TextAnalyticsWarning]
    """

    _validation = {
        'id': {'required': True},
        'sentiment': {'required': True},
        'confidence_scores': {'required': True},
        'sentences': {'required': True},
        'warnings': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'sentiment': {'key': 'sentiment', 'type': 'DocumentSentimentValue'},
        'statistics': {'key': 'statistics', 'type': 'DocumentStatistics'},
        'confidence_scores': {'key': 'confidenceScores', 'type': 'SentimentConfidenceScorePerLabel'},
        'sentences': {'key': 'sentences', 'type': '[SentenceSentiment]'},
        'warnings': {'key': 'warnings', 'type': '[TextAnalyticsWarning]'},
    }

    def __init__(self, **kwargs):
        super(DocumentSentiment, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.sentiment = kwargs.get('sentiment', None)
        self.statistics = kwargs.get('statistics', None)
        self.confidence_scores = kwargs.get('confidence_scores', None)
        self.sentences = kwargs.get('sentences', None)
        self.warnings = kwargs.get('warnings', None)


class DocumentStatistics(Model):
    """if showStats=true was specified in the request this field will contain
    information about the document payload.

    All required parameters must be populated in order to send to Azure.

    :param characters_count: Required. Number of text elements recognized in
     the document.
    :type characters_count: int
    :param transactions_count: Required. Number of transactions for the
     document.
    :type transactions_count: int
    """

    _validation = {
        'characters_count': {'required': True},
        'transactions_count': {'required': True},
    }

    _attribute_map = {
        'characters_count': {'key': 'charactersCount', 'type': 'int'},
        'transactions_count': {'key': 'transactionsCount', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(DocumentStatistics, self).__init__(**kwargs)
        self.characters_count = kwargs.get('characters_count', None)
        self.transactions_count = kwargs.get('transactions_count', None)


class EntitiesResult(Model):
    """EntitiesResult.

    All required parameters must be populated in order to send to Azure.

    :param documents: Required. Response by document
    :type documents:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentEntities]
    :param errors: Required. Errors by document id.
    :type errors:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentError]
    :param statistics:
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.RequestStatistics
    :param model_version: Required. This field indicates which model is used
     for scoring.
    :type model_version: str
    """

    _validation = {
        'documents': {'required': True},
        'errors': {'required': True},
        'model_version': {'required': True},
    }

    _attribute_map = {
        'documents': {'key': 'documents', 'type': '[DocumentEntities]'},
        'errors': {'key': 'errors', 'type': '[DocumentError]'},
        'statistics': {'key': 'statistics', 'type': 'RequestStatistics'},
        'model_version': {'key': 'modelVersion', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(EntitiesResult, self).__init__(**kwargs)
        self.documents = kwargs.get('documents', None)
        self.errors = kwargs.get('errors', None)
        self.statistics = kwargs.get('statistics', None)
        self.model_version = kwargs.get('model_version', None)


class Entity(Model):
    """Entity.

    All required parameters must be populated in order to send to Azure.

    :param text: Required. Entity text as appears in the request.
    :type text: str
    :param category: Required. Entity type, such as Person/Location/Org/SSN
     etc
    :type category: str
    :param subcategory: Entity sub type, such as Age/Year/TimeRange etc
    :type subcategory: str
    :param offset: Required. Start position for the entity text.
    :type offset: int
    :param length: Required. Length for the entity text.
    :type length: int
    :param confidence_score: Required. Confidence score between 0 and 1 of the
     extracted entity.
    :type confidence_score: float
    """

    _validation = {
        'text': {'required': True},
        'category': {'required': True},
        'offset': {'required': True},
        'length': {'required': True},
        'confidence_score': {'required': True},
    }

    _attribute_map = {
        'text': {'key': 'text', 'type': 'str'},
        'category': {'key': 'category', 'type': 'str'},
        'subcategory': {'key': 'subcategory', 'type': 'str'},
        'offset': {'key': 'offset', 'type': 'int'},
        'length': {'key': 'length', 'type': 'int'},
        'confidence_score': {'key': 'confidenceScore', 'type': 'float'},
    }

    def __init__(self, **kwargs):
        super(Entity, self).__init__(**kwargs)
        self.text = kwargs.get('text', None)
        self.category = kwargs.get('category', None)
        self.subcategory = kwargs.get('subcategory', None)
        self.offset = kwargs.get('offset', None)
        self.length = kwargs.get('length', None)
        self.confidence_score = kwargs.get('confidence_score', None)


class EntityLinkingResult(Model):
    """EntityLinkingResult.

    All required parameters must be populated in order to send to Azure.

    :param documents: Required. Response by document
    :type documents:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentLinkedEntities]
    :param errors: Required. Errors by document id.
    :type errors:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentError]
    :param statistics:
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.RequestStatistics
    :param model_version: Required. This field indicates which model is used
     for scoring.
    :type model_version: str
    """

    _validation = {
        'documents': {'required': True},
        'errors': {'required': True},
        'model_version': {'required': True},
    }

    _attribute_map = {
        'documents': {'key': 'documents', 'type': '[DocumentLinkedEntities]'},
        'errors': {'key': 'errors', 'type': '[DocumentError]'},
        'statistics': {'key': 'statistics', 'type': 'RequestStatistics'},
        'model_version': {'key': 'modelVersion', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(EntityLinkingResult, self).__init__(**kwargs)
        self.documents = kwargs.get('documents', None)
        self.errors = kwargs.get('errors', None)
        self.statistics = kwargs.get('statistics', None)
        self.model_version = kwargs.get('model_version', None)


class ErrorResponse(Model):
    """ErrorResponse.

    All required parameters must be populated in order to send to Azure.

    :param error: Required. Document Error.
    :type error:
     ~azure.ai.textanalytics.v3_1_preview_2.models.TextAnalyticsError
    """

    _validation = {
        'error': {'required': True},
    }

    _attribute_map = {
        'error': {'key': 'error', 'type': 'TextAnalyticsError'},
    }

    def __init__(self, **kwargs):
        super(ErrorResponse, self).__init__(**kwargs)
        self.error = kwargs.get('error', None)


class ErrorResponseException(HttpOperationError):
    """Server responsed with exception of type: 'ErrorResponse'.

    :param deserialize: A deserializer
    :param response: Server response to be deserialized.
    """

    def __init__(self, deserialize, response, *args):

        super(ErrorResponseException, self).__init__(deserialize, response, 'ErrorResponse', *args)


class InnerError(Model):
    """InnerError.

    All required parameters must be populated in order to send to Azure.

    :param code: Required. Error code. Possible values include:
     'InvalidParameterValue', 'InvalidRequestBodyFormat', 'EmptyRequest',
     'MissingInputRecords', 'InvalidDocument', 'ModelVersionIncorrect',
     'InvalidDocumentBatch', 'UnsupportedLanguageCode', 'InvalidCountryHint'
    :type code: str or
     ~azure.ai.textanalytics.v3_1_preview_2.models.InnerErrorCodeValue
    :param message: Required. Error message.
    :type message: str
    :param details: Error details.
    :type details: dict[str, str]
    :param target: Error target.
    :type target: str
    :param innererror: Inner error contains more specific information.
    :type innererror: ~azure.ai.textanalytics.v3_1_preview_2.models.InnerError
    """

    _validation = {
        'code': {'required': True},
        'message': {'required': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'details': {'key': 'details', 'type': '{str}'},
        'target': {'key': 'target', 'type': 'str'},
        'innererror': {'key': 'innererror', 'type': 'InnerError'},
    }

    def __init__(self, **kwargs):
        super(InnerError, self).__init__(**kwargs)
        self.code = kwargs.get('code', None)
        self.message = kwargs.get('message', None)
        self.details = kwargs.get('details', None)
        self.target = kwargs.get('target', None)
        self.innererror = kwargs.get('innererror', None)


class KeyPhraseResult(Model):
    """KeyPhraseResult.

    All required parameters must be populated in order to send to Azure.

    :param documents: Required. Response by document
    :type documents:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentKeyPhrases]
    :param errors: Required. Errors by document id.
    :type errors:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentError]
    :param statistics:
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.RequestStatistics
    :param model_version: Required. This field indicates which model is used
     for scoring.
    :type model_version: str
    """

    _validation = {
        'documents': {'required': True},
        'errors': {'required': True},
        'model_version': {'required': True},
    }

    _attribute_map = {
        'documents': {'key': 'documents', 'type': '[DocumentKeyPhrases]'},
        'errors': {'key': 'errors', 'type': '[DocumentError]'},
        'statistics': {'key': 'statistics', 'type': 'RequestStatistics'},
        'model_version': {'key': 'modelVersion', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(KeyPhraseResult, self).__init__(**kwargs)
        self.documents = kwargs.get('documents', None)
        self.errors = kwargs.get('errors', None)
        self.statistics = kwargs.get('statistics', None)
        self.model_version = kwargs.get('model_version', None)


class LanguageBatchInput(Model):
    """LanguageBatchInput.

    All required parameters must be populated in order to send to Azure.

    :param documents: Required.
    :type documents:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.LanguageInput]
    """

    _validation = {
        'documents': {'required': True},
    }

    _attribute_map = {
        'documents': {'key': 'documents', 'type': '[LanguageInput]'},
    }

    def __init__(self, **kwargs):
        super(LanguageBatchInput, self).__init__(**kwargs)
        self.documents = kwargs.get('documents', None)


class LanguageInput(Model):
    """LanguageInput.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. Unique, non-empty document identifier.
    :type id: str
    :param text: Required.
    :type text: str
    :param country_hint:
    :type country_hint: str
    """

    _validation = {
        'id': {'required': True},
        'text': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'text': {'key': 'text', 'type': 'str'},
        'country_hint': {'key': 'countryHint', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(LanguageInput, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.text = kwargs.get('text', None)
        self.country_hint = kwargs.get('country_hint', None)


class LanguageResult(Model):
    """LanguageResult.

    All required parameters must be populated in order to send to Azure.

    :param documents: Required. Response by document
    :type documents:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentLanguage]
    :param errors: Required. Errors by document id.
    :type errors:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentError]
    :param statistics:
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.RequestStatistics
    :param model_version: Required. This field indicates which model is used
     for scoring.
    :type model_version: str
    """

    _validation = {
        'documents': {'required': True},
        'errors': {'required': True},
        'model_version': {'required': True},
    }

    _attribute_map = {
        'documents': {'key': 'documents', 'type': '[DocumentLanguage]'},
        'errors': {'key': 'errors', 'type': '[DocumentError]'},
        'statistics': {'key': 'statistics', 'type': 'RequestStatistics'},
        'model_version': {'key': 'modelVersion', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(LanguageResult, self).__init__(**kwargs)
        self.documents = kwargs.get('documents', None)
        self.errors = kwargs.get('errors', None)
        self.statistics = kwargs.get('statistics', None)
        self.model_version = kwargs.get('model_version', None)


class LinkedEntity(Model):
    """LinkedEntity.

    All required parameters must be populated in order to send to Azure.

    :param name: Required. Entity Linking formal name.
    :type name: str
    :param matches: Required. List of instances this entity appears in the
     text.
    :type matches: list[~azure.ai.textanalytics.v3_1_preview_2.models.Match]
    :param language: Required. Language used in the data source.
    :type language: str
    :param id: Unique identifier of the recognized entity from the data
     source.
    :type id: str
    :param url: Required. URL for the entity's page from the data source.
    :type url: str
    :param data_source: Required. Data source used to extract entity linking,
     such as Wiki/Bing etc.
    :type data_source: str
    :param bing_id: Bing unique identifier of the recognized entity. Use in
     conjunction with the Bing Entity Search API to fetch additional relevant
     information.
    :type bing_id: str
    """

    _validation = {
        'name': {'required': True},
        'matches': {'required': True},
        'language': {'required': True},
        'url': {'required': True},
        'data_source': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'matches': {'key': 'matches', 'type': '[Match]'},
        'language': {'key': 'language', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'url': {'key': 'url', 'type': 'str'},
        'data_source': {'key': 'dataSource', 'type': 'str'},
        'bing_id': {'key': 'bingId', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(LinkedEntity, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.matches = kwargs.get('matches', None)
        self.language = kwargs.get('language', None)
        self.id = kwargs.get('id', None)
        self.url = kwargs.get('url', None)
        self.data_source = kwargs.get('data_source', None)
        self.bing_id = kwargs.get('bing_id', None)


class Match(Model):
    """Match.

    All required parameters must be populated in order to send to Azure.

    :param confidence_score: Required. If a well-known item is recognized, a
     decimal number denoting the confidence level between 0 and 1 will be
     returned.
    :type confidence_score: float
    :param text: Required. Entity text as appears in the request.
    :type text: str
    :param offset: Required. Start position for the entity match text.
    :type offset: int
    :param length: Required. Length for the entity match text.
    :type length: int
    """

    _validation = {
        'confidence_score': {'required': True},
        'text': {'required': True},
        'offset': {'required': True},
        'length': {'required': True},
    }

    _attribute_map = {
        'confidence_score': {'key': 'confidenceScore', 'type': 'float'},
        'text': {'key': 'text', 'type': 'str'},
        'offset': {'key': 'offset', 'type': 'int'},
        'length': {'key': 'length', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(Match, self).__init__(**kwargs)
        self.confidence_score = kwargs.get('confidence_score', None)
        self.text = kwargs.get('text', None)
        self.offset = kwargs.get('offset', None)
        self.length = kwargs.get('length', None)


class MultiLanguageBatchInput(Model):
    """Contains a set of input documents to be analyzed by the service.

    All required parameters must be populated in order to send to Azure.

    :param documents: Required. The set of documents to process as part of
     this batch.
    :type documents:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.MultiLanguageInput]
    """

    _validation = {
        'documents': {'required': True},
    }

    _attribute_map = {
        'documents': {'key': 'documents', 'type': '[MultiLanguageInput]'},
    }

    def __init__(self, **kwargs):
        super(MultiLanguageBatchInput, self).__init__(**kwargs)
        self.documents = kwargs.get('documents', None)


class MultiLanguageInput(Model):
    """Contains an input document to be analyzed by the service.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. A unique, non-empty document identifier.
    :type id: str
    :param text: Required. The input text to process.
    :type text: str
    :param language: (Optional) This is the 2 letter ISO 639-1 representation
     of a language. For example, use "en" for English; "es" for Spanish etc. If
     not set, use "en" for English as default.
    :type language: str
    """

    _validation = {
        'id': {'required': True},
        'text': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'text': {'key': 'text', 'type': 'str'},
        'language': {'key': 'language', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(MultiLanguageInput, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.text = kwargs.get('text', None)
        self.language = kwargs.get('language', None)


class PiiDocumentEntities(Model):
    """PiiDocumentEntities.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. Unique, non-empty document identifier.
    :type id: str
    :param redacted_text: Required. Returns redacted text.
    :type redacted_text: str
    :param entities: Required. Recognized entities in the document.
    :type entities: list[~azure.ai.textanalytics.v3_1_preview_2.models.Entity]
    :param warnings: Required. Warnings encountered while processing document.
    :type warnings:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.TextAnalyticsWarning]
    :param statistics: if showStats=true was specified in the request this
     field will contain information about the document payload.
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.DocumentStatistics
    """

    _validation = {
        'id': {'required': True},
        'redacted_text': {'required': True},
        'entities': {'required': True},
        'warnings': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'redacted_text': {'key': 'redactedText', 'type': 'str'},
        'entities': {'key': 'entities', 'type': '[Entity]'},
        'warnings': {'key': 'warnings', 'type': '[TextAnalyticsWarning]'},
        'statistics': {'key': 'statistics', 'type': 'DocumentStatistics'},
    }

    def __init__(self, **kwargs):
        super(PiiDocumentEntities, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.redacted_text = kwargs.get('redacted_text', None)
        self.entities = kwargs.get('entities', None)
        self.warnings = kwargs.get('warnings', None)
        self.statistics = kwargs.get('statistics', None)


class PiiEntitiesResult(Model):
    """PiiEntitiesResult.

    All required parameters must be populated in order to send to Azure.

    :param documents: Required. Response by document
    :type documents:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.PiiDocumentEntities]
    :param errors: Required. Errors by document id.
    :type errors:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentError]
    :param statistics:
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.RequestStatistics
    :param model_version: Required. This field indicates which model is used
     for scoring.
    :type model_version: str
    """

    _validation = {
        'documents': {'required': True},
        'errors': {'required': True},
        'model_version': {'required': True},
    }

    _attribute_map = {
        'documents': {'key': 'documents', 'type': '[PiiDocumentEntities]'},
        'errors': {'key': 'errors', 'type': '[DocumentError]'},
        'statistics': {'key': 'statistics', 'type': 'RequestStatistics'},
        'model_version': {'key': 'modelVersion', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(PiiEntitiesResult, self).__init__(**kwargs)
        self.documents = kwargs.get('documents', None)
        self.errors = kwargs.get('errors', None)
        self.statistics = kwargs.get('statistics', None)
        self.model_version = kwargs.get('model_version', None)


class RequestStatistics(Model):
    """if showStats=true was specified in the request this field will contain
    information about the request payload.

    All required parameters must be populated in order to send to Azure.

    :param documents_count: Required. Number of documents submitted in the
     request.
    :type documents_count: int
    :param valid_documents_count: Required. Number of valid documents. This
     excludes empty, over-size limit or non-supported languages documents.
    :type valid_documents_count: int
    :param erroneous_documents_count: Required. Number of invalid documents.
     This includes empty, over-size limit or non-supported languages documents.
    :type erroneous_documents_count: int
    :param transactions_count: Required. Number of transactions for the
     request.
    :type transactions_count: long
    """

    _validation = {
        'documents_count': {'required': True},
        'valid_documents_count': {'required': True},
        'erroneous_documents_count': {'required': True},
        'transactions_count': {'required': True},
    }

    _attribute_map = {
        'documents_count': {'key': 'documentsCount', 'type': 'int'},
        'valid_documents_count': {'key': 'validDocumentsCount', 'type': 'int'},
        'erroneous_documents_count': {'key': 'erroneousDocumentsCount', 'type': 'int'},
        'transactions_count': {'key': 'transactionsCount', 'type': 'long'},
    }

    def __init__(self, **kwargs):
        super(RequestStatistics, self).__init__(**kwargs)
        self.documents_count = kwargs.get('documents_count', None)
        self.valid_documents_count = kwargs.get('valid_documents_count', None)
        self.erroneous_documents_count = kwargs.get('erroneous_documents_count', None)
        self.transactions_count = kwargs.get('transactions_count', None)


class SentenceAspect(Model):
    """SentenceAspect.

    All required parameters must be populated in order to send to Azure.

    :param sentiment: Required. Aspect level sentiment for the aspect in the
     sentence. Possible values include: 'positive', 'mixed', 'negative'
    :type sentiment: str or
     ~azure.ai.textanalytics.v3_1_preview_2.models.TokenSentimentValue
    :param confidence_scores: Required. Aspect level sentiment confidence
     scores for the aspect in the sentence.
    :type confidence_scores:
     ~azure.ai.textanalytics.v3_1_preview_2.models.AspectConfidenceScoreLabel
    :param offset: Required. The aspect offset from the start of the sentence.
    :type offset: int
    :param length: Required. The length of the aspect.
    :type length: int
    :param text: Required. The aspect text detected.
    :type text: str
    :param relations: Required. The array of either opinion or aspect object
     which is related to the aspect.
    :type relations:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.AspectRelation]
    """

    _validation = {
        'sentiment': {'required': True},
        'confidence_scores': {'required': True},
        'offset': {'required': True},
        'length': {'required': True},
        'text': {'required': True},
        'relations': {'required': True},
    }

    _attribute_map = {
        'sentiment': {'key': 'sentiment', 'type': 'TokenSentimentValue'},
        'confidence_scores': {'key': 'confidenceScores', 'type': 'AspectConfidenceScoreLabel'},
        'offset': {'key': 'offset', 'type': 'int'},
        'length': {'key': 'length', 'type': 'int'},
        'text': {'key': 'text', 'type': 'str'},
        'relations': {'key': 'relations', 'type': '[AspectRelation]'},
    }

    def __init__(self, **kwargs):
        super(SentenceAspect, self).__init__(**kwargs)
        self.sentiment = kwargs.get('sentiment', None)
        self.confidence_scores = kwargs.get('confidence_scores', None)
        self.offset = kwargs.get('offset', None)
        self.length = kwargs.get('length', None)
        self.text = kwargs.get('text', None)
        self.relations = kwargs.get('relations', None)


class SentenceOpinion(Model):
    """SentenceOpinion.

    All required parameters must be populated in order to send to Azure.

    :param sentiment: Required. Opinion level sentiment for the aspect in the
     sentence. Possible values include: 'positive', 'mixed', 'negative'
    :type sentiment: str or
     ~azure.ai.textanalytics.v3_1_preview_2.models.TokenSentimentValue
    :param confidence_scores: Required. Opinion level sentiment confidence
     scores for the aspect in the sentence.
    :type confidence_scores:
     ~azure.ai.textanalytics.v3_1_preview_2.models.AspectConfidenceScoreLabel
    :param offset: Required. The opinion offset from the start of the
     sentence.
    :type offset: int
    :param length: Required. The length of the opinion.
    :type length: int
    :param text: Required. The aspect text detected.
    :type text: str
    :param is_negated: Required. The indicator representing if the opinion is
     negated.
    :type is_negated: bool
    """

    _validation = {
        'sentiment': {'required': True},
        'confidence_scores': {'required': True},
        'offset': {'required': True},
        'length': {'required': True},
        'text': {'required': True},
        'is_negated': {'required': True},
    }

    _attribute_map = {
        'sentiment': {'key': 'sentiment', 'type': 'TokenSentimentValue'},
        'confidence_scores': {'key': 'confidenceScores', 'type': 'AspectConfidenceScoreLabel'},
        'offset': {'key': 'offset', 'type': 'int'},
        'length': {'key': 'length', 'type': 'int'},
        'text': {'key': 'text', 'type': 'str'},
        'is_negated': {'key': 'isNegated', 'type': 'bool'},
    }

    def __init__(self, **kwargs):
        super(SentenceOpinion, self).__init__(**kwargs)
        self.sentiment = kwargs.get('sentiment', None)
        self.confidence_scores = kwargs.get('confidence_scores', None)
        self.offset = kwargs.get('offset', None)
        self.length = kwargs.get('length', None)
        self.text = kwargs.get('text', None)
        self.is_negated = kwargs.get('is_negated', None)


class SentenceSentiment(Model):
    """SentenceSentiment.

    All required parameters must be populated in order to send to Azure.

    :param text: Required. The sentence text.
    :type text: str
    :param sentiment: Required. The predicted Sentiment for the sentence.
     Possible values include: 'positive', 'neutral', 'negative'
    :type sentiment: str or
     ~azure.ai.textanalytics.v3_1_preview_2.models.SentenceSentimentValue
    :param confidence_scores: Required. The sentiment confidence score between
     0 and 1 for the sentence for all classes.
    :type confidence_scores:
     ~azure.ai.textanalytics.v3_1_preview_2.models.SentimentConfidenceScorePerLabel
    :param offset: Required. The sentence offset from the start of the
     document.
    :type offset: int
    :param length: Required. The length of the sentence.
    :type length: int
    :param aspects: The array of aspect object for the sentence.
    :type aspects:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.SentenceAspect]
    :param opinions: The array of opinion object for the sentence.
    :type opinions:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.SentenceOpinion]
    """

    _validation = {
        'text': {'required': True},
        'sentiment': {'required': True},
        'confidence_scores': {'required': True},
        'offset': {'required': True},
        'length': {'required': True},
    }

    _attribute_map = {
        'text': {'key': 'text', 'type': 'str'},
        'sentiment': {'key': 'sentiment', 'type': 'SentenceSentimentValue'},
        'confidence_scores': {'key': 'confidenceScores', 'type': 'SentimentConfidenceScorePerLabel'},
        'offset': {'key': 'offset', 'type': 'int'},
        'length': {'key': 'length', 'type': 'int'},
        'aspects': {'key': 'aspects', 'type': '[SentenceAspect]'},
        'opinions': {'key': 'opinions', 'type': '[SentenceOpinion]'},
    }

    def __init__(self, **kwargs):
        super(SentenceSentiment, self).__init__(**kwargs)
        self.text = kwargs.get('text', None)
        self.sentiment = kwargs.get('sentiment', None)
        self.confidence_scores = kwargs.get('confidence_scores', None)
        self.offset = kwargs.get('offset', None)
        self.length = kwargs.get('length', None)
        self.aspects = kwargs.get('aspects', None)
        self.opinions = kwargs.get('opinions', None)


class SentimentConfidenceScorePerLabel(Model):
    """Represents the confidence scores between 0 and 1 across all sentiment
    classes: positive, neutral, negative.

    All required parameters must be populated in order to send to Azure.

    :param positive: Required.
    :type positive: float
    :param neutral: Required.
    :type neutral: float
    :param negative: Required.
    :type negative: float
    """

    _validation = {
        'positive': {'required': True},
        'neutral': {'required': True},
        'negative': {'required': True},
    }

    _attribute_map = {
        'positive': {'key': 'positive', 'type': 'float'},
        'neutral': {'key': 'neutral', 'type': 'float'},
        'negative': {'key': 'negative', 'type': 'float'},
    }

    def __init__(self, **kwargs):
        super(SentimentConfidenceScorePerLabel, self).__init__(**kwargs)
        self.positive = kwargs.get('positive', None)
        self.neutral = kwargs.get('neutral', None)
        self.negative = kwargs.get('negative', None)


class SentimentResponse(Model):
    """SentimentResponse.

    All required parameters must be populated in order to send to Azure.

    :param documents: Required. Sentiment analysis per document.
    :type documents:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentSentiment]
    :param errors: Required. Errors by document id.
    :type errors:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.DocumentError]
    :param statistics:
    :type statistics:
     ~azure.ai.textanalytics.v3_1_preview_2.models.RequestStatistics
    :param model_version: Required. This field indicates which model is used
     for scoring.
    :type model_version: str
    """

    _validation = {
        'documents': {'required': True},
        'errors': {'required': True},
        'model_version': {'required': True},
    }

    _attribute_map = {
        'documents': {'key': 'documents', 'type': '[DocumentSentiment]'},
        'errors': {'key': 'errors', 'type': '[DocumentError]'},
        'statistics': {'key': 'statistics', 'type': 'RequestStatistics'},
        'model_version': {'key': 'modelVersion', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(SentimentResponse, self).__init__(**kwargs)
        self.documents = kwargs.get('documents', None)
        self.errors = kwargs.get('errors', None)
        self.statistics = kwargs.get('statistics', None)
        self.model_version = kwargs.get('model_version', None)


class TextAnalyticsError(Model):
    """TextAnalyticsError.

    All required parameters must be populated in order to send to Azure.

    :param code: Required. Error code. Possible values include:
     'InvalidRequest', 'InvalidArgument', 'InternalServerError',
     'ServiceUnavailable'
    :type code: str or
     ~azure.ai.textanalytics.v3_1_preview_2.models.ErrorCodeValue
    :param message: Required. Error message.
    :type message: str
    :param target: Error target.
    :type target: str
    :param innererror: Inner error contains more specific information.
    :type innererror: ~azure.ai.textanalytics.v3_1_preview_2.models.InnerError
    :param details: Details about specific errors that led to this reported
     error.
    :type details:
     list[~azure.ai.textanalytics.v3_1_preview_2.models.TextAnalyticsError]
    """

    _validation = {
        'code': {'required': True},
        'message': {'required': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'target': {'key': 'target', 'type': 'str'},
        'innererror': {'key': 'innererror', 'type': 'InnerError'},
        'details': {'key': 'details', 'type': '[TextAnalyticsError]'},
    }

    def __init__(self, **kwargs):
        super(TextAnalyticsError, self).__init__(**kwargs)
        self.code = kwargs.get('code', None)
        self.message = kwargs.get('message', None)
        self.target = kwargs.get('target', None)
        self.innererror = kwargs.get('innererror', None)
        self.details = kwargs.get('details', None)


class TextAnalyticsWarning(Model):
    """TextAnalyticsWarning.

    All required parameters must be populated in order to send to Azure.

    :param code: Required. Error code. Possible values include:
     'LongWordsInDocument', 'DocumentTruncated'
    :type code: str or
     ~azure.ai.textanalytics.v3_1_preview_2.models.WarningCodeValue
    :param message: Required. Warning message.
    :type message: str
    :param target_ref: A JSON pointer reference indicating the target object.
    :type target_ref: str
    """

    _validation = {
        'code': {'required': True},
        'message': {'required': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'target_ref': {'key': 'targetRef', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(TextAnalyticsWarning, self).__init__(**kwargs)
        self.code = kwargs.get('code', None)
        self.message = kwargs.get('message', None)
        self.target_ref = kwargs.get('target_ref', None)
