# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class EndpointStatus(str, Enum):

    enabled = "Enabled"
    disabled = "Disabled"


class EndpointMonitorStatus(str, Enum):

    checking_endpoint = "CheckingEndpoint"
    online = "Online"
    degraded = "Degraded"
    disabled = "Disabled"
    inactive = "Inactive"
    stopped = "Stopped"


class ProfileMonitorStatus(str, Enum):

    checking_endpoints = "CheckingEndpoints"
    online = "Online"
    degraded = "Degraded"
    disabled = "Disabled"
    inactive = "Inactive"


class MonitorProtocol(str, Enum):

    http = "HTTP"
    https = "HTTPS"
    tcp = "TCP"


class ProfileStatus(str, Enum):

    enabled = "Enabled"
    disabled = "Disabled"


class TrafficRoutingMethod(str, Enum):

    performance = "Performance"
    priority = "Priority"
    weighted = "Weighted"
    geographic = "Geographic"
    multi_value = "MultiValue"
    subnet = "Subnet"


class TrafficViewEnrollmentStatus(str, Enum):

    enabled = "Enabled"
    disabled = "Disabled"


class AllowedEndpointRecordType(str, Enum):

    domain_name = "DomainName"
    ipv4_address = "IPv4Address"
    ipv6_address = "IPv6Address"
    any = "Any"


class IdentityType(str, Enum):

    user = "User"
    application = "Application"
    managed_identity = "ManagedIdentity"
    key = "Key"
