# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AssessedDisk
    from ._models_py3 import AssessedMachine
    from ._models_py3 import AssessedMachineResultList
    from ._models_py3 import AssessedNetworkAdapter
    from ._models_py3 import Assessment
    from ._models_py3 import AssessmentOptionsResultList
    from ._models_py3 import AssessmentResultList
    from ._models_py3 import CheckNameAvailabilityParameters
    from ._models_py3 import CheckNameAvailabilityResult
    from ._models_py3 import CloudError, CloudErrorException
    from ._models_py3 import CloudErrorBody
    from ._models_py3 import Disk
    from ._models_py3 import DownloadUrl
    from ._models_py3 import Group
    from ._models_py3 import GroupResultList
    from ._models_py3 import Machine
    from ._models_py3 import MachineResultList
    from ._models_py3 import NetworkAdapter
    from ._models_py3 import Operation
    from ._models_py3 import OperationDisplay
    from ._models_py3 import OperationResultList
    from ._models_py3 import Project
    from ._models_py3 import ProjectKey
    from ._models_py3 import ProjectResultList
    from ._models_py3 import VmFamily
except (SyntaxError, ImportError):
    from ._models import AssessedDisk
    from ._models import AssessedMachine
    from ._models import AssessedMachineResultList
    from ._models import AssessedNetworkAdapter
    from ._models import Assessment
    from ._models import AssessmentOptionsResultList
    from ._models import AssessmentResultList
    from ._models import CheckNameAvailabilityParameters
    from ._models import CheckNameAvailabilityResult
    from ._models import CloudError, CloudErrorException
    from ._models import CloudErrorBody
    from ._models import Disk
    from ._models import DownloadUrl
    from ._models import Group
    from ._models import GroupResultList
    from ._models import Machine
    from ._models import MachineResultList
    from ._models import NetworkAdapter
    from ._models import Operation
    from ._models import OperationDisplay
    from ._models import OperationResultList
    from ._models import Project
    from ._models import ProjectKey
    from ._models import ProjectResultList
    from ._models import VmFamily
from ._azure_migrate_enums import (
    AssessmentSizingCriterion,
    AssessmentStage,
    AssessmentStatus,
    AzureDiskSize,
    AzureDiskSuitabilityExplanation,
    AzureDiskType,
    AzureHybridUseBenefit,
    AzureLocation,
    AzureNetworkAdapterSuitabilityExplanation,
    AzureOfferCode,
    AzurePricingTier,
    AzureStorageRedundancy,
    AzureVmSize,
    AzureVmSuitabilityExplanation,
    CloudSuitability,
    Currency,
    DiscoveryStatus,
    MachineBootType,
    NameAvailabilityReason,
    Percentile,
    ProvisioningState,
    TimeRange,
)

__all__ = [
    'AssessedDisk',
    'AssessedMachine',
    'AssessedMachineResultList',
    'AssessedNetworkAdapter',
    'Assessment',
    'AssessmentOptionsResultList',
    'AssessmentResultList',
    'CheckNameAvailabilityParameters',
    'CheckNameAvailabilityResult',
    'CloudError', 'CloudErrorException',
    'CloudErrorBody',
    'Disk',
    'DownloadUrl',
    'Group',
    'GroupResultList',
    'Machine',
    'MachineResultList',
    'NetworkAdapter',
    'Operation',
    'OperationDisplay',
    'OperationResultList',
    'Project',
    'ProjectKey',
    'ProjectResultList',
    'VmFamily',
    'DiscoveryStatus',
    'ProvisioningState',
    'AzureLocation',
    'AzureOfferCode',
    'AzurePricingTier',
    'AzureStorageRedundancy',
    'Percentile',
    'TimeRange',
    'AssessmentStage',
    'Currency',
    'AzureHybridUseBenefit',
    'AssessmentSizingCriterion',
    'AssessmentStatus',
    'MachineBootType',
    'AzureDiskType',
    'AzureDiskSize',
    'CloudSuitability',
    'AzureDiskSuitabilityExplanation',
    'AzureNetworkAdapterSuitabilityExplanation',
    'AzureVmSize',
    'AzureVmSuitabilityExplanation',
    'NameAvailabilityReason',
]
