# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class CreatedByType(str, Enum):

    user = "User"
    application = "Application"
    managed_identity = "ManagedIdentity"
    key = "Key"


class LastModifiedByType(str, Enum):

    user = "User"
    application = "Application"
    managed_identity = "ManagedIdentity"
    key = "Key"


class InvitationStatus(str, Enum):

    pending = "Pending"
    rejected = "Rejected"
    accepted = "Accepted"


class DataProcessingStrategy(str, Enum):

    copy_based = "CopyBased"
    in_place = "InPlace"


class ProvisioningState(str, Enum):

    succeeded = "Succeeded"
    creating = "Creating"
    updating = "Updating"
    deleting = "Deleting"
    moving = "Moving"
    failed = "Failed"


class DataMovementExecutionStage(str, Enum):

    input = "Input"
    output = "Output"


class LogLevel(str, Enum):

    verbose = "Verbose"
    information = "Information"
    warning = "Warning"
    error = "Error"
    critical = "Critical"


class ResourceType(str, Enum):

    data_asset_reference = "DataAssetReference"
    script_reference = "ScriptReference"


class Type(str, Enum):

    system_assigned = "SystemAssigned"


class Status(str, Enum):

    accepted = "Accepted"
    in_progress = "InProgress"
    transient_failure = "TransientFailure"
    succeeded = "Succeeded"
    failed = "Failed"
    canceled = "Canceled"


class ProposalApprovalStatus(str, Enum):

    pending = "Pending"
    approved = "Approved"
    expired = "Expired"


class PipelineRunMode(str, Enum):

    production = "Production"
    test = "Test"


class PipelineRunStatus(str, Enum):

    succeeded = "Succeeded"
    failed = "Failed"
    in_progress = "InProgress"
    preparing = "Preparing"
    queued = "Queued"
    unknown = "Unknown"
    cancelled = "Cancelled"
    canceling = "Canceling"


class PipelineStepRunStatus(str, Enum):

    succeeded = "Succeeded"
    failed = "Failed"
    in_progress = "InProgress"
    preparing = "Preparing"
    queued = "Queued"
    unknown = "Unknown"
    cancelled = "Cancelled"
    canceling = "Canceling"


class ExecutionStatus(str, Enum):

    succeeded = "Succeeded"
    failed = "Failed"
    in_progress = "InProgress"
    preparing = "Preparing"
    queued = "Queued"
    unknown = "Unknown"
    cancelled = "Cancelled"
    canceling = "Canceling"


class ContractStatus(str, Enum):

    draft = "Draft"
    active = "Active"


class ScriptKind(str, Enum):

    synapse_spark = "SynapseSpark"


class ScriptVisibility(str, Enum):

    show_all = "ShowAll"
    hidden_content = "HiddenContent"


class ExecutorNodeSize(str, Enum):

    none = "None"
    small = "Small"
    medium = "Medium"
    large = "Large"
    xlarge = "XLarge"
    xx_large = "XXLarge"
    xxx_large = "XXXLarge"


class Family(str, Enum):

    compute = "Compute"
    storage = "Storage"


class NodeSize(str, Enum):

    none = "None"
    small = "Small"
    medium = "Medium"
    large = "Large"
    xlarge = "XLarge"
    xx_large = "XXLarge"
    xxx_large = "XXXLarge"


class NodeSizeFamily(str, Enum):

    none = "None"
    memory_optimized = "MemoryOptimized"


class Visibility(str, Enum):

    show_all = "ShowAll"
    hidden_content = "HiddenContent"
