# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import SDKClient
from msrest import Serializer, Deserializer

from azure.profiles import KnownProfiles, ProfileDefinition
from azure.profiles.multiapiclient import MultiApiClientMixin
from ._configuration import OperationalInsightsManagementClientConfiguration
from ._operations_mixin import OperationalInsightsManagementClientOperationsMixin


class OperationalInsightsManagementClient(OperationalInsightsManagementClientOperationsMixin, MultiApiClientMixin, SDKClient):
    """Operational Insights Client

    This ready contains multiple API versions, to help you deal with all Azure clouds
    (Azure Stack, Azure Government, Azure China, etc.).
    By default, uses latest API version available on public Azure.
    For production, you should stick a particular api-version and/or profile.
    The profile sets a mapping between the operation group and an API version.
    The api-version parameter sets the default API version if the operation
    group is not described in the profile.

    :ivar config: Configuration for client.
    :vartype config: OperationalInsightsManagementClientConfiguration

    :param credentials: Credentials needed for the client to connect to Azure.
    :type credentials: :mod:`A msrestazure Credentials
     object<msrestazure.azure_active_directory>`
    :param subscription_id: Subscription credentials which uniquely identify
     Microsoft Azure subscription. The subscription ID forms part of the URI
     for every service call.
    :type subscription_id: str
    :param str api_version: API version to use if no profile is provided, or if
     missing in profile.
    :param str base_url: Service URL
    :param profile: A profile definition, from KnownProfiles to dict.
    :type profile: azure.profiles.KnownProfiles
    """

    DEFAULT_API_VERSION = '2015-03-20'
    _PROFILE_TAG = "azure.mgmt.loganalytics.OperationalInsightsManagementClient"
    LATEST_PROFILE = ProfileDefinition({
        _PROFILE_TAG: {
            None: DEFAULT_API_VERSION,
        }},
        _PROFILE_TAG + " latest"
    )

    def __init__(self, credentials, subscription_id, api_version=None, base_url=None, profile=KnownProfiles.default):
        self.config = OperationalInsightsManagementClientConfiguration(credentials, subscription_id, base_url)
        super(OperationalInsightsManagementClient, self).__init__(
            credentials,
            self.config,
            api_version=api_version,
            profile=profile
        )

    @classmethod
    def _models_dict(cls, api_version):
        return {k: v for k, v in cls.models(api_version).__dict__.items() if isinstance(v, type)}

    @classmethod
    def models(cls, api_version=DEFAULT_API_VERSION):
        """Module depends on the API version:

           * 2015-03-20: :mod:`v2015_03_20.models<azure.mgmt.loganalytics.v2015_03_20.models>`
           * 2015-11-01-preview: :mod:`v2015_11_01_preview.models<azure.mgmt.loganalytics.v2015_11_01_preview.models>`
           * 2019-08-01-preview: :mod:`v2019_08_01_preview.models<azure.mgmt.loganalytics.v2019_08_01_preview.models>`
        """
        if api_version == '2015-03-20':
            from .v2015_03_20 import models
            return models
        elif api_version == '2015-11-01-preview':
            from .v2015_11_01_preview import models
            return models
        elif api_version == '2019-08-01-preview':
            from .v2019_08_01_preview import models
            return models
        raise NotImplementedError("APIVersion {} is not available".format(api_version))

    @property
    def clusters(self):
        """Instance depends on the API version:

           * 2019-08-01-preview: :class:`ClustersOperations<azure.mgmt.loganalytics.v2019_08_01_preview.operations.ClustersOperations>`
        """
        api_version = self._get_api_version('clusters')
        if api_version == '2019-08-01-preview':
            from .v2019_08_01_preview.operations import ClustersOperations as OperationClass
        else:
            raise NotImplementedError("APIVersion {} is not available".format(api_version))
        return OperationClass(self._client, self.config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    @property
    def data_export(self):
        """Instance depends on the API version:

           * 2019-08-01-preview: :class:`DataExportOperations<azure.mgmt.loganalytics.v2019_08_01_preview.operations.DataExportOperations>`
        """
        api_version = self._get_api_version('data_export')
        if api_version == '2019-08-01-preview':
            from .v2019_08_01_preview.operations import DataExportOperations as OperationClass
        else:
            raise NotImplementedError("APIVersion {} is not available".format(api_version))
        return OperationClass(self._client, self.config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    @property
    def data_sources(self):
        """Instance depends on the API version:

           * 2015-11-01-preview: :class:`DataSourcesOperations<azure.mgmt.loganalytics.v2015_11_01_preview.operations.DataSourcesOperations>`
        """
        api_version = self._get_api_version('data_sources')
        if api_version == '2015-11-01-preview':
            from .v2015_11_01_preview.operations import DataSourcesOperations as OperationClass
        else:
            raise NotImplementedError("APIVersion {} is not available".format(api_version))
        return OperationClass(self._client, self.config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    @property
    def linked_services(self):
        """Instance depends on the API version:

           * 2015-11-01-preview: :class:`LinkedServicesOperations<azure.mgmt.loganalytics.v2015_11_01_preview.operations.LinkedServicesOperations>`
           * 2019-08-01-preview: :class:`LinkedServicesOperations<azure.mgmt.loganalytics.v2019_08_01_preview.operations.LinkedServicesOperations>`
        """
        api_version = self._get_api_version('linked_services')
        if api_version == '2015-11-01-preview':
            from .v2015_11_01_preview.operations import LinkedServicesOperations as OperationClass
        elif api_version == '2019-08-01-preview':
            from .v2019_08_01_preview.operations import LinkedServicesOperations as OperationClass
        else:
            raise NotImplementedError("APIVersion {} is not available".format(api_version))
        return OperationClass(self._client, self.config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    @property
    def linked_storage_accounts(self):
        """Instance depends on the API version:

           * 2019-08-01-preview: :class:`LinkedStorageAccountsOperations<azure.mgmt.loganalytics.v2019_08_01_preview.operations.LinkedStorageAccountsOperations>`
        """
        api_version = self._get_api_version('linked_storage_accounts')
        if api_version == '2019-08-01-preview':
            from .v2019_08_01_preview.operations import LinkedStorageAccountsOperations as OperationClass
        else:
            raise NotImplementedError("APIVersion {} is not available".format(api_version))
        return OperationClass(self._client, self.config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    @property
    def operations(self):
        """Instance depends on the API version:

           * 2015-03-20: :class:`Operations<azure.mgmt.loganalytics.v2015_03_20.operations.Operations>`
           * 2015-11-01-preview: :class:`Operations<azure.mgmt.loganalytics.v2015_11_01_preview.operations.Operations>`
        """
        api_version = self._get_api_version('operations')
        if api_version == '2015-03-20':
            from .v2015_03_20.operations import Operations as OperationClass
        elif api_version == '2015-11-01-preview':
            from .v2015_11_01_preview.operations import Operations as OperationClass
        else:
            raise NotImplementedError("APIVersion {} is not available".format(api_version))
        return OperationClass(self._client, self.config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    @property
    def saved_searches(self):
        """Instance depends on the API version:

           * 2015-03-20: :class:`SavedSearchesOperations<azure.mgmt.loganalytics.v2015_03_20.operations.SavedSearchesOperations>`
        """
        api_version = self._get_api_version('saved_searches')
        if api_version == '2015-03-20':
            from .v2015_03_20.operations import SavedSearchesOperations as OperationClass
        else:
            raise NotImplementedError("APIVersion {} is not available".format(api_version))
        return OperationClass(self._client, self.config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    @property
    def storage_insights(self):
        """Instance depends on the API version:

           * 2015-03-20: :class:`StorageInsightsOperations<azure.mgmt.loganalytics.v2015_03_20.operations.StorageInsightsOperations>`
        """
        api_version = self._get_api_version('storage_insights')
        if api_version == '2015-03-20':
            from .v2015_03_20.operations import StorageInsightsOperations as OperationClass
        else:
            raise NotImplementedError("APIVersion {} is not available".format(api_version))
        return OperationClass(self._client, self.config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    @property
    def workspaces(self):
        """Instance depends on the API version:

           * 2015-03-20: :class:`WorkspacesOperations<azure.mgmt.loganalytics.v2015_03_20.operations.WorkspacesOperations>`
           * 2015-11-01-preview: :class:`WorkspacesOperations<azure.mgmt.loganalytics.v2015_11_01_preview.operations.WorkspacesOperations>`
        """
        api_version = self._get_api_version('workspaces')
        if api_version == '2015-03-20':
            from .v2015_03_20.operations import WorkspacesOperations as OperationClass
        elif api_version == '2015-11-01-preview':
            from .v2015_11_01_preview.operations import WorkspacesOperations as OperationClass
        else:
            raise NotImplementedError("APIVersion {} is not available".format(api_version))
        return OperationClass(self._client, self.config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))
