# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import SDKClient
from msrest import Serializer, Deserializer

from ._configuration import EventGridPublisherClientConfiguration
from .operations import EventGridPublisherClientOperationsMixin
from msrest.exceptions import HttpOperationError
from . import models


class EventGridPublisherClient(EventGridPublisherClientOperationsMixin, SDKClient):
    """EventGrid Python Publisher Client

    :ivar config: Configuration for client.
    :vartype config: EventGridPublisherClientConfiguration

    """

    def __init__(
            self):

        self.config = EventGridPublisherClientConfiguration()
        super(EventGridPublisherClient, self).__init__(None, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self.api_version = '2018-01-01'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

