# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class RehydrationStatus(str, Enum):

    create_in_progress = "CREATE_IN_PROGRESS"
    completed = "COMPLETED"
    delete_in_progress = "DELETE_IN_PROGRESS"
    deleted = "DELETED"
    failed = "FAILED"


class RehydrationPriority(str, Enum):

    invalid = "Invalid"
    high = "High"
    standard = "Standard"


class SourceDataStoreType(str, Enum):

    archive_store = "ArchiveStore"
    snapshot_store = "SnapshotStore"
    vault_store = "VaultStore"


class DataStoreTypes(str, Enum):

    archive_store = "ArchiveStore"
    snapshot_store = "SnapshotStore"
    vault_store = "VaultStore"


class Status(str, Enum):

    configuring_protection = "ConfiguringProtection"
    configuring_protection_failed = "ConfiguringProtectionFailed"
    protection_configured = "ProtectionConfigured"
    protection_stopped = "ProtectionStopped"
    soft_deleted = "SoftDeleted"
    soft_deleting = "SoftDeleting"


class ProvisioningState(str, Enum):

    failed = "Failed"
    provisioning = "Provisioning"
    succeeded = "Succeeded"
    unknown = "Unknown"
    updating = "Updating"


class StorageSettingTypes(str, Enum):

    geo_redundant = "GeoRedundant"
    locally_redundant = "LocallyRedundant"


class RestoreTargetLocationType(str, Enum):

    invalid = "Invalid"
    azure_blobs = "AzureBlobs"
    azure_files = "AzureFiles"


class AbsoluteMarker(str, Enum):

    all_backup = "AllBackup"
    first_of_day = "FirstOfDay"
    first_of_month = "FirstOfMonth"
    first_of_week = "FirstOfWeek"
    first_of_year = "FirstOfYear"


class DayOfWeek(str, Enum):

    friday = "Friday"
    monday = "Monday"
    saturday = "Saturday"
    sunday = "Sunday"
    thursday = "Thursday"
    tuesday = "Tuesday"
    wednesday = "Wednesday"


class Month(str, Enum):

    april = "April"
    august = "August"
    december = "December"
    february = "February"
    january = "January"
    july = "July"
    june = "June"
    march = "March"
    may = "May"
    november = "November"
    october = "October"
    september = "September"


class WeekNumber(str, Enum):

    first = "First"
    fourth = "Fourth"
    last = "Last"
    second = "Second"
    third = "Third"
