# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------
from msrestazure import AzureConfiguration

from .version import VERSION


class AzureDeviceUpdateClientConfiguration(AzureConfiguration):
    """Configuration for AzureDeviceUpdateClient
    Note that all parameters used to create this instance are saved as instance
    attributes.

    :param credentials: Credentials needed for the client to connect to Azure.
    :type credentials: :mod:`A msrestazure Credentials
     object<msrestazure.azure_active_directory>`
    :param account_endpoint: Account endpoint.
    :type account_endpoint: str
    :param instance_id: Account instance identifier.
    :type instance_id: str
    """

    def __init__(
            self, credentials, account_endpoint, instance_id):

        if credentials is None:
            raise ValueError("Parameter 'credentials' must not be None.")
        if account_endpoint is None:
            raise ValueError("Parameter 'account_endpoint' must not be None.")
        if instance_id is None:
            raise ValueError("Parameter 'instance_id' must not be None.")
        base_url = 'https://{accountEndpoint}'

        super(AzureDeviceUpdateClientConfiguration, self).__init__(base_url)

        # Starting Autorest.Python 4.0.64, make connection pool activated by default
        self.keep_alive = True

        self.add_user_agent('deviceupdate/{}'.format(VERSION))
        self.add_user_agent('Azure-SDK-For-Python')

        self.credentials = credentials
        self.account_endpoint = account_endpoint
        self.instance_id = instance_id
