# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import CreateGenericQuotaRequestParameters
    from ._models_py3 import CurrentQuotaLimit
    from ._models_py3 import CurrentQuotaLimitBase
    from ._models_py3 import ExceptionResponse, ExceptionResponseException
    from ._models_py3 import QuotaLimitsResponse
    from ._models_py3 import QuotaProperties
    from ._models_py3 import QuotaRequestDetails
    from ._models_py3 import QuotaRequestOneResourceSubmitResponse
    from ._models_py3 import QuotaRequestProperties
    from ._models_py3 import QuotaRequestSubmitResponse
    from ._models_py3 import QuotaRequestSubmitResponse201
    from ._models_py3 import ResourceName
    from ._models_py3 import ServiceError
    from ._models_py3 import ServiceErrorDetail
    from ._models_py3 import SubRequest
except (SyntaxError, ImportError):
    from ._models import CreateGenericQuotaRequestParameters
    from ._models import CurrentQuotaLimit
    from ._models import CurrentQuotaLimitBase
    from ._models import ExceptionResponse, ExceptionResponseException
    from ._models import QuotaLimitsResponse
    from ._models import QuotaProperties
    from ._models import QuotaRequestDetails
    from ._models import QuotaRequestOneResourceSubmitResponse
    from ._models import QuotaRequestProperties
    from ._models import QuotaRequestSubmitResponse
    from ._models import QuotaRequestSubmitResponse201
    from ._models import ResourceName
    from ._models import ServiceError
    from ._models import ServiceErrorDetail
    from ._models import SubRequest
from ._paged_models import CurrentQuotaLimitBasePaged
from ._paged_models import QuotaRequestDetailsPaged

__all__ = [
    'CreateGenericQuotaRequestParameters',
    'CurrentQuotaLimit',
    'CurrentQuotaLimitBase',
    'ExceptionResponse', 'ExceptionResponseException',
    'QuotaLimitsResponse',
    'QuotaProperties',
    'QuotaRequestDetails',
    'QuotaRequestOneResourceSubmitResponse',
    'QuotaRequestProperties',
    'QuotaRequestSubmitResponse',
    'QuotaRequestSubmitResponse201',
    'ResourceName',
    'ServiceError',
    'ServiceErrorDetail',
    'SubRequest',
    'CurrentQuotaLimitBasePaged',
    'QuotaRequestDetailsPaged',
]
